### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by t-haich** [Angblah/The-Comparator#2]
As a registered user, I want to login so I can access account-related storage, such as saving templates

**Comment by honeychawla** [comment]
While basic login functionality does work, I want to use Flask-Login to handle user sessions.

**Comment by alexyuisingwu** [comment]
- When logging in with invalid credentials, user feedback is not provided. 

- Clicking on the logo after logging in logs you out and leads you to the home page. "Not registered yet" leads to nothing (should we have a separate registration page?).

- Heading in middle says "Username's dashboard" instead of the actual username.

**Comment by honeychawla** [comment]
The heading in the middle now says the username's dashboard.

**Comment by honeychawla** [comment]
Bad credentials are now handled

**Comment by honeychawla** [comment]
Still have to handle what happens when you click on the logo when you're logged in. currently it just logs you out and takes back to home page.

**Comment by honeychawla** [comment]
Clicking the logo after you've logged in routes you to profile page instead of the home page for not logged in people!
